apiVersion: apps/v1
kind: Deployment
metadata:
  name: pl
  labels:
    app: test
spec:
  selector:
    matchLabels:
      app: test
  replicas: 3
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
      - name: test
        image: sysnet4admin/dashboard
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx/conf.d/
        - name: log-volume
          mountPath: /log          
        ports:
        - containerPort: 80
      volumes:
        - name: config-volume
          configMap:
            name: test-configmap
        - name: log-volume
          emptyDir:
            {}